title: My Github site
author: Hassib K
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
This is the awesome website I made using the help of Github.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
